package com.nianticproject.ingress.shared;

public enum ItemType {
    EMITTER_A, EMP_BURSTER, FLIP_CARD, FORCE_AMP, HEATSINK, LINK_AMPLIFIER, MEDIA, MULTIHACK,
    PORTAL_LINK_KEY, POWER_CUBE, RES_SHIELD, TURRET, UNKNOWN
}
